### ISSUE TITLE
=D ez rekt

### ISSUE THREAD

**Issue by reckendheck** [Bhupesh-V/memer-action#18]
if (meme-action = true) 
{
   self.feelgood();
} else

{
self.suicide
}

**Comment by Bhupesh-V** [comment]
> {
self.suicide
}

You ok ?

![](https://media0.giphy.com/media/gIwvjOQYS2MchdrPl4/200w.gif?cid=5a38a5a29q6zhmyjsbe2mrfumfq4ycn4dtkmjh5d7e96xu5d&rid=200w.gif)
