### ISSUE TITLE
Action is crashing

### ISSUE THREAD

**Issue by jpacareu** [Bhupesh-V/memer-action#19]
**Describe the bug**
Hi men I am receiving this error in my PRs, do you have any idea of what could be :\

```
Traceback (most recent call last):
  File "/app/main.py", line 57, in <module>
    main()
  File "/app/main.py", line 50, in main
    meme = getMeme(filter_by)
  File "/app/main.py", line 32, in getMeme
    elif os.environ["INPUT_FALLBACK"]:
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'INPUT_FALLBACK'
```
Thanks

**To Reproduce**
It's just happening 

**Expected behavior**
To work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Python Version [e.g. 3.8]
 - Memer Action Version [e.g. 0.2.0]

**Additional context**

**Comment by Bhupesh-V** [comment]
Thanks for reporting this @jpacareu 
I am debugging it, will update

**Comment by jpacareu** [comment]
Hi @Bhupesh-V any luck with this? :\

**Comment by Bhupesh-V** [comment]
Hey sorry have been busy
looks like Reddit is returning  429 (Too Many Requests) when run as a GitHub action. That's why no data is returned from the feed
I will try parse the xml feed directly without feedparser with custom request headers and see if it works out

**Comment by jpacareu** [comment]
Hi @Bhupesh-V is it true that the few moments of happiness in our PRs are gone for good? 😭  😓
